version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pg_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - ./pgData:/var/lib/psotgresql/data
  python-app:
    build:
      context: .
    depends_on:
      - db
